#!/bin/bash

darkblue="\033[1m\033[34m\033[40m"
lightblue="\033[96m\033[40m"
red="\033[31m"
green="\033[32m"
white="\033[39m"
curl https://api.coinmarketcap.com/v1/ticker/ | JSON.sh -n|awk '/\{/ { print }' |
awk -v darkblue="$darkblue" -v lightblue="$lightblue" -v white="$white" -F, '{
  gsub(/(\")/,""); gsub(/(name|symbol|rank|price.usd)\:/,""); print darkblue$2"("lightblue$3") > $"$5" | "$8" | "$9" | "$11" | "$13
}'|
awk -v red="$red" -v green="$green" -v white="$white" -F ">" '/-/    { print $1red"|"$2white; next; }
                                                             /[^-]/  { print $1green"|"$2white }' | column -t -s="|"
